### ISSUE TITLE
Uploading files gives 500 NLST not understood error

### ISSUE THREAD

**Issue by vassdeniss** [robinrodricks/FluentFTP#1409]
**FTP Server OS:** Unknown

**FTP Server Type:** Unnkown

**Client Computer OS:** Windows

**FluentFTP Version:** 48.0.3

**Framework:** .NET 8 / MAUI

I am making an app that transfers ROM saves between 2 devices given their file paths, and optionally does conversions between the files. When I upload the files to the target FTP server I get a NLST given-path not understood error.
[Link to my repo](https://github.com/vassdeniss/TransferMySaves)

**Logs :**
```
2023-12-14 15:31:47.725 +02:00 [INF] >         AutoConnect()
2023-12-14 15:31:47.748 +02:00 [INF] >         AutoDetect(CloneConnection = False, FirstOnly = True, IncludeImplicit = True, RequireEncryption = False, ProtocolPriority = [Tls11, Tls12])
2023-12-14 15:31:47.752 +02:00 [INF] Status:   Auto-Detect trying encryption mode "Auto" with "Tls11, Tls12"
2023-12-14 15:31:47.764 +02:00 [INF] >         Connect(False)
2023-12-14 15:31:47.765 +02:00 [INF] Status:   FluentFTP 48.0.3.0(.NET 6.0)
2023-12-14 15:31:47.788 +02:00 [INF] Status:   Connecting to IP #1= ***:5000
2023-12-14 15:32:08.910 +02:00 [INF] Status:   Closing/Disposing FtpSocketStream(control connection)
2023-12-14 15:32:19.078 +02:00 [INF] >         Dispose()
2023-12-14 15:32:19.079 +02:00 [INF] Status:   Disposing FtpClient object...
2023-12-14 15:32:19.079 +02:00 [INF] >         Dispose()
2023-12-14 15:32:19.079 +02:00 [INF] Status:   Disposing FtpClient object...
2023-12-14 15:32:19.079 +02:00 [INF] Status:   Closing/Disposing FtpSocketStream(control connection)
2023-12-14 15:32:20.474 +02:00 [INF] >         AutoConnect()
2023-12-14 15:32:20.475 +02:00 [INF] >         AutoDetect(CloneConnection = False, FirstOnly = True, IncludeImplicit = True, RequireEncryption = False, ProtocolPriority = [Tls11, Tls12])
2023-12-14 15:32:20.475 +02:00 [INF] Status:   Auto-Detect trying encryption mode "Auto" with "Tls11, Tls12"
2023-12-14 15:32:20.475 +02:00 [INF] >         Connect(False)
2023-12-14 15:32:20.475 +02:00 [INF] Status:   FluentFTP 48.0.3.0(.NET 6.0)
2023-12-14 15:32:20.475 +02:00 [INF] Status:   Connecting to IP #1= ***:5000
2023-12-14 15:32:23.590 +02:00 [INF] Status:   Waiting for a response
2023-12-14 15:32:23.606 +02:00 [INF] Response: 220 Hello! [738867.564d]
2023-12-14 15:32:23.610 +02:00 [INF] Command:  AUTH TLS
2023-12-14 15:32:23.612 +02:00 [INF] Status:   Waiting for response to: AUTH TLS
2023-12-14 15:32:23.617 +02:00 [INF] Response: 502 Invalid command "AUTH TLS" [5ms]
2023-12-14 15:32:23.619 +02:00 [INF] Command:  USER ***
2023-12-14 15:32:23.619 +02:00 [INF] Status:   Waiting for response to: USER ***
2023-12-14 15:32:23.625 +02:00 [INF] Response: 230 OK [6ms]
2023-12-14 15:32:23.627 +02:00 [INF] Command:  FEAT
2023-12-14 15:32:23.628 +02:00 [INF] Status:   Waiting for response to: FEAT
2023-12-14 15:32:23.736 +02:00 [INF] Response: 211-
Response: MDTM
Response: MLST Type*;Size*;Modify*;Perm*;UNIX.mode;
Response: PASV
Response: SIZE
Response: TVFS
Response: UTF8
2023-12-14 15:32:23.736 +02:00 [INF] Response: 211 End [108ms]
2023-12-14 15:32:23.747 +02:00 [INF] Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
2023-12-14 15:32:23.747 +02:00 [INF] Command:  OPTS UTF8 ON
2023-12-14 15:32:23.747 +02:00 [INF] Status:   Waiting for response to: OPTS UTF8 ON
2023-12-14 15:32:23.753 +02:00 [INF] Response: 200 OK [5ms]
2023-12-14 15:32:23.753 +02:00 [INF] Command:  SYST
2023-12-14 15:32:23.753 +02:00 [INF] Status:   Waiting for response to: SYST
2023-12-14 15:32:23.758 +02:00 [INF] Response: 215 UNIX Type: L8 [5ms]
2023-12-14 15:32:23.760 +02:00 [INF] Status:   Listing parser set to: Machine
2023-12-14 15:32:23.761 +02:00 [INF] Command:  PWD
2023-12-14 15:32:23.762 +02:00 [INF] Status:   Waiting for response to: PWD
2023-12-14 15:32:23.809 +02:00 [INF] Response: 257 "/" [46ms]
2023-12-14 15:32:23.834 +02:00 [INF] >         GetListing("/retroarch/cores/savefiles/Gambatte", ForceList)
2023-12-14 15:32:23.838 +02:00 [INF] Command:  TYPE I
2023-12-14 15:32:23.838 +02:00 [INF] Status:   Waiting for response to: TYPE I
2023-12-14 15:32:23.845 +02:00 [INF] Response: 200 OK [6ms]
2023-12-14 15:32:23.847 +02:00 [INF] >         OpenDataStreamAsync("LIST /retroarch/cores/savefiles/Gambatte", 0)
2023-12-14 15:32:23.849 +02:00 [INF] >         OpenPassiveDataStreamAsync(PASV, "LIST /retroarch/cores/savefiles/Gambatte", 0)
2023-12-14 15:32:23.850 +02:00 [INF] Command:  PASV
2023-12-14 15:32:23.850 +02:00 [INF] Status:   Waiting for response to: PASV
2023-12-14 15:32:23.858 +02:00 [INF] Response: 227 Entering Passive Mode (192,168,0,23,19,137). [8ms]
2023-12-14 15:32:23.865 +02:00 [INF] Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
2023-12-14 15:32:23.866 +02:00 [INF] Status:   Connecting to IP #1= ***:5001
2023-12-14 15:32:23.872 +02:00 [INF] Command:  LIST /retroarch/cores/savefiles/Gambatte
2023-12-14 15:32:23.872 +02:00 [INF] Status:   Waiting for response to: LIST /retroarch/cores/savefiles/Gambatte
2023-12-14 15:32:24.176 +02:00 [INF] Response: 150 Ready [303ms]
2023-12-14 15:32:24.177 +02:00 [INF] +---------------------------------------+
2023-12-14 15:32:24.273 +02:00 [INF] Listing:  -rw-rw-rw- 19184 3DS 3DS 8192 Dec 13 17:48 Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm
2023-12-14 15:32:24.273 +02:00 [INF] Listing:  -rw-rw-rw- 19184 3DS 3DS 32768 Dec 13 21:01 Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm
2023-12-14 15:32:24.273 +02:00 [INF] Listing:  -rw-rw-rw- 19184 3DS 3DS 8 Dec 13 21:01 Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc
2023-12-14 15:32:24.273 +02:00 [INF] -----------------------------------------
2023-12-14 15:32:24.273 +02:00 [INF] Status:   Closing/Disposing FtpSocketStream(data connection)
2023-12-14 15:32:24.274 +02:00 [INF] >         CloseDataStream()
2023-12-14 15:32:24.274 +02:00 [INF] Status:   Waiting for response to: LIST /retroarch/cores/savefiles/Gambatte
2023-12-14 15:32:24.275 +02:00 [INF] Response: 226 OK [403ms]
2023-12-14 15:32:24.275 +02:00 [INF] Status:   Closing/Disposing FtpSocketStream(data connection)
2023-12-14 15:32:24.278 +02:00 [INF] Status:   Detected format Unix
2023-12-14 15:32:24.292 +02:00 [INF] >         DownloadFiles("C:\Users\vassd\AppData\Local\Packages\com.companyname.transfermysaves_9zz4h110yvjzm\LocalState", System.Linq.Enumerable+SelectArrayIterator`2[FluentFTP.FtpListItem,System.String], Overwrite, Retry)
2023-12-14 15:32:24.295 +02:00 [INF] >         DownloadFile("C:\Users\vassd\AppData\Local\Packages\com.companyname.transfermysaves_9zz4h110yvjzm\LocalState\Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm", "/retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm", Overwrite, Retry)
2023-12-14 15:32:24.302 +02:00 [INF] >         GetFileSize("/retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm", -1)
2023-12-14 15:32:24.302 +02:00 [INF] Command:  SIZE /retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm
2023-12-14 15:32:24.302 +02:00 [INF] Status:   Waiting for response to: SIZE /retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm
2023-12-14 15:32:24.470 +02:00 [INF] Response: 213 8192 [167ms]
2023-12-14 15:32:24.472 +02:00 [INF] >         OpenRead("/retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm", Binary, 0, 8192)
2023-12-14 15:32:24.472 +02:00 [INF] >         OpenDataStreamAsync("RETR /retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm", 0)
2023-12-14 15:32:24.472 +02:00 [INF] >         OpenPassiveDataStreamAsync(PASV, "RETR /retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm", 0)
2023-12-14 15:32:24.472 +02:00 [INF] Command:  PASV
2023-12-14 15:32:24.472 +02:00 [INF] Status:   Waiting for response to: PASV
2023-12-14 15:32:24.479 +02:00 [INF] Response: 227 Entering Passive Mode (192,168,0,23,19,138). [6ms]
2023-12-14 15:32:24.479 +02:00 [INF] Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
2023-12-14 15:32:24.479 +02:00 [INF] Status:   Connecting to IP #1= ***:5002
2023-12-14 15:32:25.529 +02:00 [INF] Command:  RETR /retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm
2023-12-14 15:32:25.530 +02:00 [INF] Status:   Waiting for response to: RETR /retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm
2023-12-14 15:32:25.747 +02:00 [INF] Response: 150 Ready [217ms]
2023-12-14 15:32:25.787 +02:00 [INF] Status:   Downloaded 8192 bytes
2023-12-14 15:32:25.787 +02:00 [INF] Status:   Closing/Disposing FtpSocketStream(data connection)
2023-12-14 15:32:25.788 +02:00 [INF] Status:   Waiting for response to: RETR /retroarch/cores/savefiles/Gambatte/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).srm
2023-12-14 15:32:25.807 +02:00 [INF] Response: 226 OK [277ms]
2023-12-14 15:32:25.808 +02:00 [INF] Status:   File Verification: PASS
2023-12-14 15:32:25.809 +02:00 [INF] >         DownloadFile("C:\Users\vassd\AppData\Local\Packages\com.companyname.transfermysaves_9zz4h110yvjzm\LocalState\Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm", "/retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm", Overwrite, Retry)
2023-12-14 15:32:25.809 +02:00 [INF] >         GetFileSize("/retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm", -1)
2023-12-14 15:32:25.810 +02:00 [INF] Command:  SIZE /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm
2023-12-14 15:32:25.810 +02:00 [INF] Status:   Waiting for response to: SIZE /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm
2023-12-14 15:32:26.040 +02:00 [INF] Response: 213 32768 [230ms]
2023-12-14 15:32:26.041 +02:00 [INF] >         OpenRead("/retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm", Binary, 0, 32768)
2023-12-14 15:32:26.041 +02:00 [INF] >         OpenDataStreamAsync("RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm", 0)
2023-12-14 15:32:26.041 +02:00 [INF] >         OpenPassiveDataStreamAsync(PASV, "RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm", 0)
2023-12-14 15:32:26.041 +02:00 [INF] Command:  PASV
2023-12-14 15:32:26.041 +02:00 [INF] Status:   Waiting for response to: PASV
2023-12-14 15:32:26.053 +02:00 [INF] Response: 227 Entering Passive Mode (192,168,0,23,19,139). [11ms]
2023-12-14 15:32:26.053 +02:00 [INF] Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
2023-12-14 15:32:26.053 +02:00 [INF] Status:   Connecting to IP #1= ***:5003
2023-12-14 15:32:26.061 +02:00 [INF] Command:  RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm
2023-12-14 15:32:26.061 +02:00 [INF] Status:   Waiting for response to: RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm
2023-12-14 15:32:26.268 +02:00 [INF] Response: 150 Ready [206ms]
2023-12-14 15:32:26.327 +02:00 [INF] Status:   Downloaded 32768 bytes
2023-12-14 15:32:26.327 +02:00 [INF] Status:   Closing/Disposing FtpSocketStream(data connection)
2023-12-14 15:32:26.327 +02:00 [INF] Status:   Waiting for response to: RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).srm
2023-12-14 15:32:26.328 +02:00 [INF] Response: 226 OK [266ms]
2023-12-14 15:32:26.328 +02:00 [INF] Status:   File Verification: PASS
2023-12-14 15:32:26.328 +02:00 [INF] >         DownloadFile("C:\Users\vassd\AppData\Local\Packages\com.companyname.transfermysaves_9zz4h110yvjzm\LocalState\Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc", "/retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc", Overwrite, Retry)
2023-12-14 15:32:26.329 +02:00 [INF] >         GetFileSize("/retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc", -1)
2023-12-14 15:32:26.330 +02:00 [INF] Command:  SIZE /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc
2023-12-14 15:32:26.330 +02:00 [INF] Status:   Waiting for response to: SIZE /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc
2023-12-14 15:32:26.498 +02:00 [INF] Response: 213 8 [168ms]
2023-12-14 15:32:26.498 +02:00 [INF] >         OpenRead("/retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc", Binary, 0, 8)
2023-12-14 15:32:26.498 +02:00 [INF] >         OpenDataStreamAsync("RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc", 0)
2023-12-14 15:32:26.498 +02:00 [INF] >         OpenPassiveDataStreamAsync(PASV, "RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc", 0)
2023-12-14 15:32:26.498 +02:00 [INF] Command:  PASV
2023-12-14 15:32:26.498 +02:00 [INF] Status:   Waiting for response to: PASV
2023-12-14 15:32:26.503 +02:00 [INF] Response: 227 Entering Passive Mode (192,168,0,23,19,140). [5ms]
2023-12-14 15:32:26.503 +02:00 [INF] Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
2023-12-14 15:32:26.504 +02:00 [INF] Status:   Connecting to IP #1= ***:5004
2023-12-14 15:32:26.510 +02:00 [INF] Command:  RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc
2023-12-14 15:32:26.510 +02:00 [INF] Status:   Waiting for response to: RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc
2023-12-14 15:32:26.748 +02:00 [INF] Response: 150 Ready [238ms]
2023-12-14 15:32:26.756 +02:00 [INF] Status:   Downloaded 8 bytes
2023-12-14 15:32:26.758 +02:00 [INF] Status:   Closing/Disposing FtpSocketStream(data connection)
2023-12-14 15:32:26.759 +02:00 [INF] Status:   Waiting for response to: RETR /retroarch/cores/savefiles/Gambatte/Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).rtc
2023-12-14 15:32:26.800 +02:00 [INF] Response: 226 OK [289ms]
2023-12-14 15:32:26.800 +02:00 [INF] Status:   File Verification: PASS
2023-12-14 15:32:26.889 +02:00 [INF] >         AutoConnect()
2023-12-14 15:32:26.889 +02:00 [INF] >         AutoDetect(CloneConnection = False, FirstOnly = True, IncludeImplicit = True, RequireEncryption = False, ProtocolPriority = [Tls11, Tls12])
2023-12-14 15:32:26.889 +02:00 [INF] Status:   Auto-Detect trying encryption mode "Auto" with "Tls11, Tls12"
2023-12-14 15:32:26.889 +02:00 [INF] >         Connect(False)
2023-12-14 15:32:26.889 +02:00 [INF] Status:   FluentFTP 48.0.3.0(.NET 6.0)
2023-12-14 15:32:26.889 +02:00 [INF] Status:   Connecting to IP #1= ***:21
2023-12-14 15:32:27.794 +02:00 [INF] Status:   Waiting for a response
2023-12-14 15:32:27.802 +02:00 [INF] Response: 220 FTP Server Ready [738867.564d]
2023-12-14 15:32:27.802 +02:00 [INF] Command:  AUTH TLS
2023-12-14 15:32:27.802 +02:00 [INF] Status:   Waiting for response to: AUTH TLS
2023-12-14 15:32:27.851 +02:00 [INF] Response: 500 AUTH TLS not understood. [48ms]
2023-12-14 15:32:27.851 +02:00 [INF] Command:  USER ***
2023-12-14 15:32:27.851 +02:00 [INF] Status:   Waiting for response to: USER ***
2023-12-14 15:32:27.859 +02:00 [INF] Response: 331 Password required for ***. [7ms]
2023-12-14 15:32:27.859 +02:00 [INF] Command:  PASS ***
2023-12-14 15:32:27.859 +02:00 [INF] Status:   Waiting for response to: PASS ***
2023-12-14 15:32:27.867 +02:00 [INF] Response: 230 You're logged in. [7ms]
2023-12-14 15:32:27.867 +02:00 [INF] Command:  FEAT
2023-12-14 15:32:27.867 +02:00 [INF] Status:   Waiting for response to: FEAT
2023-12-14 15:32:27.899 +02:00 [INF] Response: 500 FEAT not understood. [31ms]
2023-12-14 15:32:27.899 +02:00 [INF] Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
2023-12-14 15:32:27.899 +02:00 [INF] Command:  OPTS UTF8 ON
2023-12-14 15:32:27.899 +02:00 [INF] Status:   Waiting for response to: OPTS UTF8 ON
2023-12-14 15:32:27.962 +02:00 [INF] Response: 500 OPTS UTF8 ON not understood. [62ms]
2023-12-14 15:32:27.962 +02:00 [INF] Command:  SYST
2023-12-14 15:32:27.962 +02:00 [INF] Status:   Waiting for response to: SYST
2023-12-14 15:32:27.969 +02:00 [INF] Response: 215 UNIX Type: L8 [7ms]
2023-12-14 15:32:27.970 +02:00 [INF] Status:   Listing parser set to: Unix
2023-12-14 15:32:27.970 +02:00 [INF] Command:  PWD
2023-12-14 15:32:27.970 +02:00 [INF] Status:   Waiting for response to: PWD
2023-12-14 15:32:27.978 +02:00 [INF] Response: 257 "/" is current directory. [7ms]
2023-12-14 15:32:27.985 +02:00 [INF] >         UploadFiles(System.String[], "/PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE", Overwrite, True, None, None)
2023-12-14 15:32:27.986 +02:00 [INF] >         DirectoryExists("/PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE")
2023-12-14 15:32:27.986 +02:00 [INF] Command:  CWD /PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE
2023-12-14 15:32:27.986 +02:00 [INF] Status:   Waiting for response to: CWD /PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE
2023-12-14 15:32:27.999 +02:00 [INF] Response: 250 CWD command successful. [12ms]
2023-12-14 15:32:27.999 +02:00 [INF] Command:  CWD /
2023-12-14 15:32:28.000 +02:00 [INF] Status:   Waiting for response to: CWD /
2023-12-14 15:32:28.008 +02:00 [INF] Response: 250 CWD command successful. [8ms]
2023-12-14 15:32:28.011 +02:00 [INF] >         GetNameListing("/PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE")
2023-12-14 15:32:28.011 +02:00 [INF] Command:  TYPE I
2023-12-14 15:32:28.011 +02:00 [INF] Status:   Waiting for response to: TYPE I
2023-12-14 15:32:28.023 +02:00 [INF] Response: 200 Type set to I. [11ms]
2023-12-14 15:32:28.024 +02:00 [INF] >         OpenDataStreamAsync("NLST /PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE", 0)
2023-12-14 15:32:28.024 +02:00 [INF] >         OpenPassiveDataStreamAsync(PASV, "NLST /PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE", 0)
2023-12-14 15:32:28.024 +02:00 [INF] Command:  PASV
2023-12-14 15:32:28.024 +02:00 [INF] Status:   Waiting for response to: PASV
2023-12-14 15:32:28.032 +02:00 [INF] Response: 227 Entering Passive Mode (192,168,0,32,233,87). [8ms]
2023-12-14 15:32:28.032 +02:00 [INF] Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
2023-12-14 15:32:28.032 +02:00 [INF] Status:   Connecting to IP #1= ***:59735
2023-12-14 15:32:28.040 +02:00 [INF] Command:  NLST /PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE
2023-12-14 15:32:28.040 +02:00 [INF] Status:   Waiting for response to: NLST /PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE
2023-12-14 15:32:28.049 +02:00 [INF] Response: 500 NLST /PSP/GAME/MasterBoy V2.10 Game Boy Color/Roms GBC/SAVE not understood. [8ms]
2023-12-14 15:32:28.049 +02:00 [INF] Status:   Closing/Disposing FtpSocketStream(data connection)
2023-12-14 15:32:28.049 +02:00 [INF] >         CloseDataStream()
2023-12-14 15:32:30.164 +02:00 [INF] Command:  QUIT
2023-12-14 15:32:30.164 +02:00 [INF] Status:   Waiting for response to: QUIT
2023-12-14 15:32:30.246 +02:00 [INF] Response: 221 Disconnecting [81ms]
2023-12-14 15:32:30.247 +02:00 [INF] Status:   Closing/Disposing FtpSocketStream(control connection)
2023-12-14 15:32:30.247 +02:00 [INF] Command:  QUIT
2023-12-14 15:32:30.247 +02:00 [INF] Status:   Waiting for response to: QUIT
```

**Comment by FanDjango** [comment]
There are a small number of problems that I see:

1.
FluentFTP is using the NLST command in order to check if the file exists. It should rather use the SIZE command instead. This is a known bug and has been fixed in the current master on GitHub but not yet released. Nonetheless, the NLST command is an (much slower) alternative and **should work**, but..

2.
The filenames that are to be down/uploaded contain blanks. This causes the NLST to fail on those server that do not proberly implement the RFCs. To avoid this, you could delete the file first and then upload without an overwite, maybe, so that an exitence check is not needed. Or don't use NLST, see 1.

**Comment by vassdeniss** [comment]
> There are a small number of problems that I see:
> 
> 
> FluentFTP is using the NLST command in order to check if the file exists. It should rather use the SIZE command instead. This is a known bug and has been fixed in the current master on GitHub but not yet released. Nonetheless, the NLST command is an (much slower) alternative and **should work**, but..
> 
> 
> The filenames that are to be down/uploaded contain blanks. This causes the NLST to fail on those servers that do not proberly implement the RFCs. To avoid this, you could delete the file first and then upload without an overwite, maybe, so that an exitence check is not needed. Or don't use NLST, see 1.

I will try 1 as suggested now, as per 2 it is not an overwrite, the file does not exist on the target.

**Comment by FanDjango** [comment]
I meant, `UploadFile(......, FtpRemoteExists.NoCheck, ....);`

**Comment by vassdeniss** [comment]
Interestingly enough 1 did not solve the issue but 2 did even on nuget build, what is the difference between None and Overwrite?

**Comment by FanDjango** [comment]
I would appreciate a verbose log again from using the current master - can do?

**Comment by FanDjango** [comment]
NoCheck means don't check if the file exists. Means no need to do SIZE or NLST.

**Comment by vassdeniss** [comment]
So it just transfers it and overwrites without checking at all?

**Comment by FanDjango** [comment]
Depends on the server - some will overwrite, some will refuse if the file already exists. If it doesn't exist, no problem.

RFC says STOR should not overwrite, IIRC.

**Comment by vassdeniss** [comment]
Well in any case, my issue has been resolved, thank you very much and thanks for the great library!
