### ISSUE TITLE
UploadFileAsync not working with old FTP-Server (but UploadFile works)

### ISSUE THREAD

**Issue by reureu** [robinrodricks/FluentFTP#395]
**FTP OS:** Unix

**FTP Server:** No information available, unfortunately.

**Computer OS:** : 
Windows 10 x64 (Version 1809).
.NET 4.6.1 MSIL Application.
FluentFTP 24.0.0

I'm trying to upload a simple text file to a rather old FTP server.

- It works when I use the synchronous method: "UploadFile".
- It works when I use the asynchronous method "UploadFileAsync" AND when the remote file already exists.
- But it fails when I use the asynchronous method "UploadFileSync" AND when the remote file does not exist.

**Isolation:**
- The problem occurs the vast majority of the time, although the UploadAsync method does work on rare occasions.
- The same transfer using Filezilla works all the time.
- It works when using the asynchronous method "UploadSync" to other FTP-Servers.
- The Encoding and DataType are unrelated to the problem.

Here is the InnerException:
```
FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at FluentFTP.FtpSocketStream.<ReadAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpDataStream.<ReadAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpSocketStream.<ReadLineAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<GetNameListingAsync>d__378.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<FileExistsAsync>d__458.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<UploadFileInternalAsync>d__312.MoveNext()
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.<UploadFileInternalAsync>d__312.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<UploadFileFromFileAsync>d__306.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<UploadFileAsync>d__304.MoveNext()
```

**Code:**

```
            const FtpDataType dataType = FtpDataType.ASCII;
            using (_client = new FtpClient()
            {
                Host = host,
                Credentials = new NetworkCredential(user, password),
                Encoding = Encoding.GetEncoding("ISO-8859-1"),
                UploadDataType = dataType,
                DownloadDataType = dataType,
            })
            {
                try
                {
#if false
                    Task.Run(() => _client.UploadFile(file2Upload, $"/data/TestFile.txt")).Wait();
#else
                    _client.UploadFileAsync(file2Upload, "/data/TestFile.txt").Wait();
#endif
                }
                catch (AggregateException e)
                {
                    foreach (var ie in e.InnerExceptions)
                    {
                        Console.WriteLine("*************************************************");
                        Console.WriteLine(ie);
                    }
                }
            }
```
Sorry, I don't have much info about the FTP-Server!
I understand this is an old FTP-Server, but what puzzles me is that the synchronous methods do work and not the async ones.

**Logs :**
```
# UploadFileAsync("TestFile.txt", "/data/TestFile.txt", Overwrite, False, None)

# FileExistsAsync("/data/TestFile.txt")

# Connect()
Status:   Connecting to XXXXXXXXXXXXX:21
Response: 220 Homegate FTP Server ready
Command:  USER XXXXXXXX
Response: 331 Password required for testrem
Command:  PASS ***
Response: 230 Login OK
Command:  FEAT
Response: 211 End
Response: 211-Features supported
Response: REST STREAM
Response: EPRT
Response: EPSV
Response: SIZE
Response: MDTM
Response: MFMT
Response: AUTH
Response: PBSZ
Response: PROT
Response: MLST type*;size*;modify*;
Response: MLSD
Response: UTF8
Response: MODE Z
Status:   Text encoding: System.Text.Latin1Encoding
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser
Command:  SIZE /data/TestFile.txt
Response: 550 Can't find file "TestFile.txt".
Command:  MDTM /data/TestFile.txt
Response: 550 Can't find file

# GetNameListingAsync("/data")
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStreamAsync(AutoPassive, "NLST /data", 0)
Command:  EPSV
Response: 229 Entering Passive Mode (|||63270|)
Status:   Connecting to XXXXXXXXXXXXX:63270
Command:  NLST /data
Response: 226 Transfer complete
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Status:   Disposing FtpSocketStream...
### Exception thrown: 'System.AggregateException' in mscorlib.dll

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Good-Bye
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```

**Comment by robinrodricks** [comment]
Not sure what you're doing but you can't do any parallel commands, that is, you cannot start an Async upload of file 1, and at the same time start an Async upload of file 2. You can chain them to execute one after another and that should be fine.

**Comment by reureu** [comment]
Hi Robin,

Thanks for your reply.
The `#if false` and ` #else` are just here to easily switch between both versions of the code (synchronous/asynchronous) calls.

My test program is just trivial.
It uploads only 1 file. No parallel command.

I thought the FTP-Server was the culprit until I got it working with the synchronous UploadFile method.

**Comment by reureu** [comment]
For the sake of curiosity, I generated a few dumps for the following scenarios:

1: Call of UploadFile, when the remote file does not exist on the server. This scenario works every time.
[01_Synchronous_RemoteFileNotExists_OK.txt](https://github.com/robinrodricks/FluentFTP/files/3151300/01_Synchronous_RemoteFileNotExists_OK.txt)

2: Call of UploadFileAsync, when the remote file does not exist on the server. The upload failed in this test.
[02_Asynchronous_RemoteFileNotExists_NOK.txt](https://github.com/robinrodricks/FluentFTP/files/3151301/02_Asynchronous_RemoteFileNotExists_NOK.txt)

3: Call of UploadFileAsync, when the remote file does not exist on the server. It was one of the rare upload attempts that succeeded.
[03_Asynchronous_RemoteFileNotExists_OK.txt](https://github.com/robinrodricks/FluentFTP/files/3151302/03_Asynchronous_RemoteFileNotExists_OK.txt)

4: Call of UploadFileAsync, when the remote file already exists on the server. This works every time.
[04_Asynchronous_RemoteFileExists_OK.txt](https://github.com/robinrodricks/FluentFTP/files/3151303/04_Asynchronous_RemoteFileExists_OK.txt)

I would be very pleased if the developers could have a look.

Kind regards,
Reureu

**Comment by reureu** [comment]
Ok, I managed to do a bit of debugging in FluentFTP.

The old FTP-server of our partner returns code 550 with message 

> Can't find file "TestFile.txt."

 when executing "SIZE TestFile.txt".

Part of the problem seems to be due to commit 1228d5a8.
FtpClient_Connection.cs, fileNotFoundStrings: some quotes are missing

- wrong:
`"can't find file, can't check for file existence", ...`
- correct:
`"can't find file", "can't check for file existence", ...`

Consequently, IsKnownError returns false. in FileExistsAsync.

There is also a difference in `FileExists` and `FileExistsAsync`.
- FileExists has got dedicated code to handle reply code "550" (fix #179).
- FileExistsAsync doesn't do anything special for reply code "550".

Because of both these issues, FileExistsAsync calls GetNameListingAsync which in turn tries to execute NLST and fails.

Now the next problem:
Both GetNameListingAsync and GetNameListing often throws with this old server. 
Maybe there is a race-condition somewhere in the underlying sockets?

```
# GetNameListingAsync("/data")
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStreamAsync(AutoPassive, "NLST /data", 0)
Command:  EPSV
Response: 229 Entering Passive Mode (|||62345|)
Status:   Connecting to 5.175.16.198:62345
Command:  NLST /data
Response: 226 Transfer complete
Exception thrown: 'System.IO.IOException' in System.dll
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

```
Do you guys want to fix these problems?

And another problem, probably worth another issue: 
UploadFileAsync does not honor the FtpDataType.
In our case UploadFileAsync uploads the text file as binary data despite the FtpClient.UploadDataType=ASCII.
UploadFile uploads the file in the right mode.

I hope that helps.
Kind regards,
Reureu

**Comment by robinrodricks** [comment]
Awesome work debugging this. Thanks for the detailed issue. These should be pretty easy to fix. I prioritized this task.

**Comment by reureu** [comment]
Thanks @robinrodricks !
What might not be so easy to fix is the System.IO.IOException in GetNameListing/GetNameListingAsync.
Do you intent to fix it too?

**Comment by robinrodricks** [comment]
> **Bug 1 :** FtpClient_Connection.cs, fileNotFoundStrings: some quotes are missing.

Fixed.

> **Bug 2 :** FileExistsAsync doesn't do anything special for reply code "550".

Fixed.

> **Bug 3**: GetNameListingAsync and GetNameListing often throws with this old server

Help needed!

> **Bug 4**: UploadFileAsync does not honor the FtpDataType.

I checked the code and both honor it. Maybe more debugging is needed.

------

Thanks again.

Fixes released in 25.0.0.

See notes: https://github.com/robinrodricks/FluentFTP/blob/master/RELEASES.md#2500

**Comment by robinrodricks** [comment]
@reureu please check if it works with the latest version, so I can close this issue.

**Comment by reureu** [comment]
@robinrodricks,

Thanks for fixing the first 2 bugs!

About the failing GetNameListingAsync when getting the file list in a specific folder.
- It works all the time if the folder contains any file.
- It very often fails if the folder contains no file. It does work on rare occasions though.

I tried to add a few Thread.Sleep() in a few spots to see if it was a timing issue.

I managed to see an improvement by adding a Sleep() in one spot. But that would definitely not be the right way to resolve it, and I didn't really want to debug the NetworkSocket stuffs.

So I tried the same test with WebRequestMethods.Ftp.ListDirectory (https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequestmethods.ftp.listdirectory), and saw it works all the time.

I can try to get you a test account on this old FTP server, but it will probably take a few days, as it is a bank holiday week-end in our country. That would also allow you to troubleshoot Bug 4.

Kind regards,
Reureu

**Comment by reureu** [comment]
@robinrodricks ,

I have validated the fixes of Bug 1 and 2. UploadFileAsync now works fine in our test config.

As we thought, GetNameListing and GetNameListingAsync are still throwing when the remote folder is empty.

Kind regards,
Reureu

**Comment by robinrodricks** [comment]
Thanks. I'll try to fix that one then we can close this issue.

**Comment by robinrodricks** [comment]
Hi, the latest version has fixes for Async. Can you check and see if it works?

**Comment by reureu** [comment]
Hi,
Thanks for the new releases!

GetNameListing and GetNameListingAsync are still throwing with Version 26.0.0 when the remote folder on this old FTP-server is empty.

**Comment by robinrodricks** [comment]
Hi,

Try this?

https://we.tl/t-N5nLpKDDNd

**Comment by reureu** [comment]
Still the same, with both methods GetNameListing and GetNameListingAsync.

> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
>    at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
>    at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
>    at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at FluentFTP.FtpDataStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
>    at FluentFTP.FtpClient.GetNameListing(String path)
>    at FluentFTPGetNameListingTest01.Program.Main(String[] args) in D:\source\_DummyProjects\FluentFTPGetNameListingTest01\FluentFTPGetNameListingTest01\Program.cs:line 38

**Comment by robinrodricks** [comment]
Please try this?

https://we.tl/t-LIHcaFQoW0

**Comment by reureu** [comment]
GetNameListing and GetNameListingAsync are now both working 100% in my test case with empty folders.
What did you fix? Have you already pushed the fix? Or was that just a preliminary build?

**Comment by robinrodricks** [comment]
Great. I'll push the fix to nuget soon. We fixed a case where the server would not open a port for empty folders, thereby causing our connection/authentication to crash. We now internally catch this exception and move on.

**Comment by robinrodricks** [comment]
Its live : https://www.nuget.org/packages/FluentFTP/26.0.1

**Comment by reureu** [comment]
Thanks a lot @robinrodricks !

**Comment by robinrodricks** [comment]
Your welcome.
