### ISSUE TITLE
GetObjectInfo falling back to GetListing fails when not setting path to FTP path

### ISSUE THREAD

**Issue by JosHuybrighs** [robinrodricks/FluentFTP#751]
**FTP OS:** Don't know

**FTP Server:** Don't know

**Computer OS:** Windows 10

**FluentFTP Version:** 34.0.2

When using GetObjectInfo(path) towards a server that doesn't support MLST then the check to find a match with the returned items of GetListing assumes that 'path' is set in FTP format, i.e. "/root/content/sync".

Code in GetObjectInfo, which does a wrong check for 'path':
```
var dirPath = path.GetFtpDirectoryName();
var dirItems = GetListing(dirPath);
foreach (var dirItem in dirItems) {
	if (dirItem.FullName == path) {
		result = dirItem;
		break;
	}
}
```

The overcome this error one has to call GetObjectInfo as follows:
```
var ftpPath = path.GetFtpPath();
var item = _ftpClient.GetObjectInfo(ftpPath);
```

Is this really an error or do we have to use the FTP path format everywhere in our code? I though that FluentFTP takes care of mixing forward and backward slashes.

**Comment by robinrodricks** [comment]
I have fixed it for GetObjectInfo. I will ensure all other methods are also fixed and cleanup FTP paths internally.

Please try this build:

[FluentFTP.35.0.0_BETA5.zip](https://github.com/robinrodricks/FluentFTP/files/7070451/FluentFTP.35.0.0_BETA5.zip)

**Comment by robinrodricks** [comment]
Released.

https://www.nuget.org/packages/FluentFTP/35.0.0

**Comment by robinrodricks** [comment]
Hi @JosHuybrighs, can you try the latest build from nuget and tell me if it resolves your issue? I need feedback on this please.

**Comment by AngryShaDoW** [comment]
At v35.2.0 client.GetListing() still throw null reference exception. Probably because this:
```
public FtpListItem[] GetListing()
{
    return GetListing(null);
}

public FtpListItem[] GetListing(string path, FtpListOption options)
{
...
    if (path.StartsWith("/") || ServerType != FtpServer.IBMzOSFTP || ServerOS != FtpOperatingSystem.IBMzOS)
    {
        path = GetAbsolutePath(path);
    }
...
}
```

**Comment by FanDjango** [comment]
I'll check that

**Comment by FanDjango** [comment]
Ok, I can reproduce that. Thx for the heads up, my recent z/OS changes are at fault. I'll put in a PR to fix that right away.

**Comment by robinrodricks** [comment]
Thanks for fixing this @FanDjango !

**Comment by robinrodricks** [comment]
@JosHuybrighs is this fixed and can we close this issue?
